source 'https://github.com/cocoapods/specs.git'
# Uncomment the next line to define a global platform for your project
#platform :ios, '11.0'

target 'BloodDonation' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BloodDonation

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'
  pod 'OHMySQL'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

  target 'BloodDonationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BloodDonationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
    config.build_settings.delete('CODE_SIGNING_ALLOWED')
    config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
  end

end
